/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.protos.mesage.v1.MyMessage', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.protos.mesage.v1.MyMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.protos.mesage.v1.MyMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.protos.mesage.v1.MyMessage.displayName = 'proto.protos.mesage.v1.MyMessage';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.protos.mesage.v1.MyMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.protos.mesage.v1.MyMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.protos.mesage.v1.MyMessage} msg The msg instance to transform.
 * @return {!Object}
 */
proto.protos.mesage.v1.MyMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
    field: jspb.Message.getFieldWithDefault(msg, 1, ""),
    anotherField: jspb.Message.getFieldWithDefault(msg, 2, 0),
    yetAnotherField: jspb.Message.getFieldWithDefault(msg, 3, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.protos.mesage.v1.MyMessage}
 */
proto.protos.mesage.v1.MyMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.protos.mesage.v1.MyMessage;
  return proto.protos.mesage.v1.MyMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.protos.mesage.v1.MyMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.protos.mesage.v1.MyMessage}
 */
proto.protos.mesage.v1.MyMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setField(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAnotherField(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setYetAnotherField(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.protos.mesage.v1.MyMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.protos.mesage.v1.MyMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.protos.mesage.v1.MyMessage} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.protos.mesage.v1.MyMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getField();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAnotherField();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getYetAnotherField();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
};


/**
 * optional string field = 1;
 * @return {string}
 */
proto.protos.mesage.v1.MyMessage.prototype.getField = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.protos.mesage.v1.MyMessage.prototype.setField = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional int32 another_field = 2;
 * @return {number}
 */
proto.protos.mesage.v1.MyMessage.prototype.getAnotherField = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.protos.mesage.v1.MyMessage.prototype.setAnotherField = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional bool yet_another_field = 3;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.protos.mesage.v1.MyMessage.prototype.getYetAnotherField = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 3, false));
};


/** @param {boolean} value */
proto.protos.mesage.v1.MyMessage.prototype.setYetAnotherField = function(value) {
  jspb.Message.setField(this, 3, value);
};


goog.object.extend(exports, proto.protos.mesage.v1);
