# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/v1/message/message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/v1/message/message.proto',
  package='protos.mesage.v1',
  syntax='proto3',
  serialized_pb=_b('\n\x1fprotos/v1/message/message.proto\x12\x10protos.mesage.v1\"L\n\tMyMessage\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\x15\n\ranother_field\x18\x02 \x01(\x05\x12\x19\n\x11yet_another_field\x18\x03 \x01(\x08\x42\x41Z?github.com/pablodz/protoc-generator/pkg/v1/message;pkgmessagev1b\x06proto3')
)




_MYMESSAGE = _descriptor.Descriptor(
  name='MyMessage',
  full_name='protos.mesage.v1.MyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='field', full_name='protos.mesage.v1.MyMessage.field', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='another_field', full_name='protos.mesage.v1.MyMessage.another_field', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yet_another_field', full_name='protos.mesage.v1.MyMessage.yet_another_field', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=129,
)

DESCRIPTOR.message_types_by_name['MyMessage'] = _MYMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MyMessage = _reflection.GeneratedProtocolMessageType('MyMessage', (_message.Message,), dict(
  DESCRIPTOR = _MYMESSAGE,
  __module__ = 'protos.v1.message.message_pb2'
  # @@protoc_insertion_point(class_scope:protos.mesage.v1.MyMessage)
  ))
_sym_db.RegisterMessage(MyMessage)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z?github.com/pablodz/protoc-generator/pkg/v1/message;pkgmessagev1'))
# @@protoc_insertion_point(module_scope)
