# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/v1/message/message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fprotos/v1/message/message.proto\x12\x10protos.mesage.v1\"L\n\tMyMessage\x12\r\n\x05\x66ield\x18\x01 \x01(\t\x12\x15\n\ranother_field\x18\x02 \x01(\x05\x12\x19\n\x11yet_another_field\x18\x03 \x01(\x08\x42\x41Z?github.com/pablodz/protoc-generator/pkg/v1/message;pkgmessagev1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.v1.message.message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z?github.com/pablodz/protoc-generator/pkg/v1/message;pkgmessagev1'
  _MYMESSAGE._serialized_start=53
  _MYMESSAGE._serialized_end=129
# @@protoc_insertion_point(module_scope)
